-- UPDATE

SELECT * FROM EMPLOYEE;

SELECT FIRST_NAME
FROM EMPLOYEE
WHERE ID = 1;

UPDATE EMPLOYEE
SET LAST_NAME = 'SRIVAS'
WHERE ID = 1;

SELECT * FROM EMPLOYEE;

-- DELETE

DELETE FROM EMPLOYEE
WHERE ID = 2;

-- LIKE

SELECT *
FROM EMPLOYEE
WHERE FIRST_NAME LIKE 'ABHI%';

SELECT *
FROM EMPLOYEE
WHERE FIRST_NAME LIKE 'ABHILAS__';


-- LIMIT AND OFFSET
-- used to limit the amount of data returned by the select statement
-- OFFSET provides offset for the start of the LIMIT
SELECT *
FROM EMPLOYEE
LIMIT 3;

SELECT *
FROM EMPLOYEE
LIMIT 3 OFFSET 2;


-- ORDER BY
SELECT *
FROM EMPLOYEE
ORDER BY AGE ASC;

-- WITH CLAUSE
WITH new_table AS (
    SELECT FIRST_NAME, LAST_NAME
    FROM EMPLOYEE
    WHERE AGE>32
)
SELECT * FROM new_table;

SELECT * FROM EMPLOYEE;

-- There are following common CONSTRAINTS:
-- NOT NULL
-- UNIQUE
-- PRIMARY KEY
-- FOREIGN KEY
-- CHECK CONSTRAINT

ALTER TABLE EMPLOYEE
ADD CONSTRAINT first_name_unique_constraint UNIQUE(FIRST_NAME);

-- INDEX
CREATE INDEX MY_INDEX ON EMPLOYEE(FIRST_NAME);

-- VIEWS
CREATE VIEW employee_view AS
SELECT * FROM EMPLOYEE WHERE AGE>32;

SELECT * FROM employee_view;

DROP VIEW employee_view;
